"""Supplementary figures S5 (ipSAE reproducibility, reduced) and S7 (helical-bias panels).

Fig S4 (structural clustering) is produced by jobs/tm_cluster.py as a TM-align dendrogram —
the authoritative version. The earlier DSSP-feature S4 that lived here was superseded once
TM-align was approved, and was removed so re-running this script can't clobber the good figure."""
import numpy as np, pandas as pd, matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from pathlib import Path
from scipy.cluster.hierarchy import linkage, dendrogram, fcluster
from scipy import stats
ROOT = Path("/Users/amyhe/Desktop/trem2_2026/agents_vs_humans_paper")
RES = ROOT / "analyses/structure_epitope/results"; FIG = ROOT / "analyses/structure_epitope/figures"
AGENT, HUMAN, BIND, NON, INK = "#30C5F5", "#1FE48F", "#00D9FF", "#5C6773", "#0F1419"
plt.rcParams.update({"font.size": 9, "axes.edgecolor": INK, "axes.linewidth": 0.6,
                     "axes.spines.top": False, "axes.spines.right": False, "figure.dpi": 300})
meta = pd.read_parquet(ROOT / "analyses/structure_epitope/data/designs_canonical.parquet")
df = pd.read_parquet(ROOT / "data/designs.parquet")

# Fig S4 (structural clustering) is generated by jobs/tm_cluster.py as a TM-align dendrogram.
# We only load fold_topology here because Fig S7 below needs it.
fold = pd.read_csv(RES / "fold_topology.csv")

# ============ S5: ipSAE reproducibility (reduced: cross-method, no per-seed ensemble) ============
d = df[["design_id","submitted_ipsae","px_ipsae_d0chn_max","chai_ipsae_d0chn_max","submitted_to_lab"]].copy()
d["ipsae_min"] = d[["submitted_ipsae","px_ipsae_d0chn_max","chai_ipsae_d0chn_max"]].min(axis=1)
d["ipsae_max"] = d[["submitted_ipsae","px_ipsae_d0chn_max","chai_ipsae_d0chn_max"]].max(axis=1)
d["ipsae_spread"] = d.ipsae_max - d.ipsae_min
d = d.dropna(subset=["submitted_ipsae"]).sort_values("submitted_ipsae").reset_index(drop=True)
fig, (a1, a2) = plt.subplots(1, 2, figsize=(11, 3.6))
a1.errorbar(range(len(d)), (d.ipsae_min+d.ipsae_max)/2, yerr=(d.ipsae_max-d.ipsae_min)/2,
            fmt="none", ecolor="#CBD5E0", elinewidth=0.7)
a1.scatter(range(len(d)), d.submitted_ipsae, s=8, color="#33C4FF", label="competition (Boltz-2)", zorder=3)
a1.set_xlabel("design (ranked by competition ipSAE)"); a1.set_ylabel("ipSAE")
a1.set_title(f"(a) ipSAE across methods (Boltz-2/Protenix/Chai)\nmedian spread {d.ipsae_spread.median():.2f}",
             fontsize=8, loc="left"); a1.legend(frameon=False, fontsize=7)
# rank stability: competition rank vs protenix rank, top-100 cutoff
d2 = df.dropna(subset=["submitted_ipsae"]).copy()
d2["rank_comp"] = d2.submitted_ipsae.rank(ascending=False)
d2["rank_px"] = d2.px_ipsae_d0chn_max.rank(ascending=False)
a2.scatter(d2.rank_comp, d2.rank_px, s=10, c=[AGENT if x else HUMAN for x in (d2.cohort=="agent")], edgecolor=INK, linewidth=0.2)
a2.axvline(100, color="#FF4628", ls="--", lw=0.8); a2.axhline(100, color="#FF4628", ls="--", lw=0.8)
crossers = int(((d2.rank_comp<=100)&(d2.rank_px>100)).sum())
a2.set_xlabel("competition ipSAE rank"); a2.set_ylabel("Protenix ipSAE rank")
a2.set_title(f"(b) rank stability vs predictor\n{crossers} of top-100 fall outside Protenix top-100",
             fontsize=8, loc="left")
tau = stats.kendalltau(d2.rank_comp, d2.rank_px)[0]
a2.text(0.05, 0.92, f"Kendall τ={tau:.2f}", transform=a2.transAxes, fontsize=8)
fig.suptitle("Fig S4. ipSAE reproducibility (cross-method proxy; no per-seed ensemble exists in the data package)",
             fontsize=8.5, x=0.01, ha="left")
fig.tight_layout(rect=[0,0,1,0.95]); fig.savefig(FIG / "figS4_ipsae_reproducibility.png", bbox_inches="tight"); plt.close(fig)

# ============ S7: helical bias ============
h = fold.merge(df[["design_id","submitted_ipsae"]], on="design_id")  # fold already has method_family
fig, axs = plt.subplots(1, 3, figsize=(12, 3.4))
axs[0].hist(h.helix_frac.dropna(), bins=20, color="#33C4FF", edgecolor=INK, linewidth=0.3)
axs[0].axvline(h.helix_frac.median(), color=INK, ls="--", lw=0.8)
axs[0].set_xlabel("binder helix fraction (DSSP)"); axs[0].set_ylabel("designs")
axs[0].set_title(f"(a) helix fraction, all 141\nmedian {h.helix_frac.median():.2f}; {int((h.strand_frac>0.2).sum())} with β>20%",
                 fontsize=8, loc="left")
hh = h.dropna(subset=["submitted_ipsae","helix_frac"])
px = hh[hh.method_family=="PXDesign"]
axs[1].scatter(hh.helix_frac, hh.submitted_ipsae, s=10, color="#CBD5E0", label="all")
axs[1].scatter(px.helix_frac, px.submitted_ipsae, s=14, color="#FF4628", label="PXDesign", zorder=3)
axs[1].set_xlabel("helix fraction"); axs[1].set_ylabel("ipSAE")
r_all=stats.spearmanr(hh.helix_frac,hh.submitted_ipsae)[0]; r_px=stats.spearmanr(px.helix_frac,px.submitted_ipsae)[0]
axs[1].set_title(f"(b) ipSAE vs helicity\nall ρ={r_all:.2f} but within-PXDesign ρ={r_px:.2f}", fontsize=8, loc="left")
axs[1].legend(frameon=False, fontsize=7)
e = h[h.p_expressed==True]
bp = axs[2].boxplot([e[e.is_hit==False].helix_frac.dropna(), e[e.is_hit==True].helix_frac.dropna()],
                    tick_labels=["non-binder","binder"], patch_artist=True, widths=0.6)
for patch, c in zip(bp["boxes"], [NON, BIND]): patch.set_facecolor(c)
for m in bp["medians"]: m.set_color(INK)
axs[2].set_ylabel("helix fraction"); axs[2].set_title("(c) helicity does not predict binding\n(ρ=0.19, p=0.08)", fontsize=8, loc="left")
fig.suptitle("Fig S7. α-helical bias — ipSAE tracks helicity (ρ=0.44) but the effect is a between-tool confound "
             "(vanishes within PXDesign) and helicity barely predicts binding.", fontsize=8.2, x=0.01, ha="left")
fig.tight_layout(rect=[0,0,1,0.95]); None  # dropped former-FigS7 (helical bias), omitted; plt.close(fig)
print("wrote figS5, figS7 (figS4 is produced by jobs/tm_cluster.py)")
print(f"S5: {crossers} of competition top-100 fall outside Protenix top-100; Kendall τ={tau:.2f}; median ipSAE spread {d.ipsae_spread.median():.2f}")
